apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-canary
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
        track: canary
        version: 1.9.1
    spec:
      containers:
      - name: httpd
        image: docker.io/httpd
        ports:
        - containerPort: 80
